tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "cocoapods"
brew "dnsmasq", restart_service: true
brew "git"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "php@8.1", restart_service: true
brew "php@8.0", restart_service: true
brew "php@7.4", restart_service: true
brew "yarn"
brew "gh"
brew "redis"

cask "1password"
cask "alfred"
cask "anydesk"
cask "cron"
cask "devtoys"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flux"
cask "github"
cask "google-chrome"
cask "hammerspoon"
cask "helo"
cask "insomnia"
cask "iterm2"
cask "loom"
cask "notion"
cask "ray"
cask "rocket"
cask "runjs"
cask "sketch"
cask "slack"
cask "spotify"
cask "tableplus"
cask "telegram"
# TODO: Things 3
cask "tinkerwell"
cask "tuple"
cask "tweetbot"
cask "visual-studio-code"
cask "zoom"
