#!/bin/bash
set -euo pipefail

# Display message 'Cleaning up your Mac...'
echo "Cleaning up your Mac..."
sudo -v

# Brew cleanup
brew update
brew upgrade
brew cleanup

# Removed local versions of deleted/merged Git branches
for d in ~/Sites/*/; do cd $d; echo WORKING ON $d; git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d; cd ..; done
for d in ~/Projects/*/; do cd $d; echo WORKING ON $d; git branch --merged master | grep -v "\* master" | xargs -n 1 git branch -d; cd ..; done

# Delete `node_modules` folders older than 120 days
find . -name "node_modules" -type d -mtime +120 | xargs rm -rf

# Complete
echo "Cleanup Complete"
