alias migrate="valet php artisan migrate"
alias fresh="valet php artisan migrate:fresh"
alias seed="valet php artisan db:seed"
alias hor="valet php artisan horizon"
alias dusk="valet php artisan dusk"
alias duskf="dusk --filter"
