alias p="valet php please"
alias pnew="statamic new"
alias puser="cp ~/.dotfiles/statamic/duncan@statamic.com.yaml users/duncan@statamic.com.yaml"
alias puserme="cp ~/.dotfiles/statamic/duncan@duncanmcclean.com.yaml users/duncan@duncanmcclean.com.yaml"
alias pdeets="valet php please support:details"
alias psc="valet php please stache:clear"
